### ISSUE TITLE
Working with Flukso FLM02A?

### ISSUE THREAD

**Issue by andbez** [bertouttier/flukso-hacs#1]
Just installed your new integration for Home Assistant. Got it working and entered Device-Hashes (I think you mean the "Sensor Identification", don't you?). But nothing is shown in Home Assistant. Only the Integration-Page shows, that I configured it. Does it work with my Flukso-Model FLM02A?

Any Hints?

Thank you.

**Comment by bertouttier** [comment]
No the device hash is not a sensor hash. The device has can be found using an MQTT client and listening to topic ```/device/+/test/tap```. The device hash is the second part of the topic.

Hope this helps!

**Comment by andbez** [comment]
Thank you for your answer. Unfortunately there is never a top like /device/*. Only /sensor/+/counter or /sensor/+/gauge, where + is the ID of the sensor. I am using an older Flukso-Device and installed MQTT as described in the Flusko-Forum. Regarding this Documentation (https://github.com/gebhardm/flm03/blob/main/MQTT.md) the MQTT-Topics are different between Version 2 and 3 of Flukso. Did you develop this piece of Software with a newer Flukso-Device (Version 3)?

**Comment by vk2him** [comment]
I have a Version 2A and I also can't get this to work - I tried using the sensor ID and when that didn't work, i used MQTT Explorer and found a hash similar to what you described, however that also doesn't work. I get the following error  in the supervisor logs:

Logger: homeassistant.components.sensor
Source: custom_components/flukso/discovery.py:348
Integration: Sensor (documentation, issues)
First occurred: 7:47:09 PM (1 occurrences)
Last logged: 7:47:09 PM

Error while setting up flukso platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/flukso/sensor.py", line 10, in async_setup_entry
    configs = get_entities_for_platform("sensor", hass.data[DOMAIN][entry.entry_id])
  File "/config/custom_components/flukso/discovery.py", line 372, in get_entities_for_platform
    entities.extend(_get_sensor_entities(entry_data, device_info))
  File "/config/custom_components/flukso/discovery.py", line 348, in _get_sensor_entities
    entities.append(MQTT_SENSOR_PLATFORM_SCHEMA(config))
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected SensorStateClass for dictionary value @ data['state_class']

**Comment by bertouttier** [comment]
> Thank you for your answer. Unfortunately there is never a top like /device/*. Only /sensor/+/counter or /sensor/+/gauge, where + is the ID of the sensor. I am using an older Flukso-Device and installed MQTT as described in the Flusko-Forum. Regarding this Documentation (https://github.com/gebhardm/flm03/blob/main/MQTT.md) the MQTT-Topics are different between Version 2 and 3 of Flukso. Did you develop this piece of Software with a newer Flukso-Device (Version 3)?

Indeed, I developed it for FLM03, not version 02. I will check with Flukso if we can easily support version 02 as well.

**Comment by bertouttier** [comment]
@vk2him Which version of HA are you using?

Could you test with the newest version 1.0.1? Can you add the debug logs?

**Comment by andbez** [comment]
Just added my Flukso V02 as Sensors in HA. May be this would help you for your development.
```
- platform: mqtt
  unique_id: fxxxxxxb12-cf84-4225-8e25-fa091111180e
  state_topic: "/sensor/sensorid/gauge"
  device_class: energy
  name: "Aktueller Stromverbrauch"
  qos: 0
  unit_of_measurement: "W"
  value_template: '{{ value_json[1] }}'

- platform: mqtt
  unique_id: xxxxxxxxxx-60e8-42c0-8bd1-6f37c785ae9f
  state_topic: "/sensor/sensorid/counter"
  device_class: energy
  name: "Summe Stromverbrauch"
  qos: 0
  unit_of_measurement: "Wh"
  value_template: "{{ value_json[1] }}"

- platform: mqtt
  unique_id: xxxxxxx-53ac-4a4a-bc0c-7c9f8fee2144
  state_topic: "/sensor/sensorid/counter"
  device_class: gas
  name: "Summe Gasverbrauch"
  qos: 0
  unit_of_measurement: "m3"
  value_template: '{{ value_json[1] }}'

- platform: mqtt
  unique_id: xxxxxxxxx-6e24-42bf-b49f-2168ea27cf6b
  state_topic: "/sensor/sensorid/counter"
  name: "Summe Wasserverbrauch"
  qos: 0
  unit_of_measurement: "m3"
  value_template: '{{ value_json[1] }}'
```

**Comment by bertouttier** [comment]
> Just added my Flukso V02 as Sensors in HA. May be this would help you for your development.
> 
> ```
> - platform: mqtt
>   unique_id: fxxxxxxb12-cf84-4225-8e25-fa091111180e
>   state_topic: "/sensor/sensorid/gauge"
>   device_class: energy
>   name: "Aktueller Stromverbrauch"
>   qos: 0
>   unit_of_measurement: "W"
>   value_template: '{{ value_json[1] }}'
> 
> - platform: mqtt
>   unique_id: xxxxxxxxxx-60e8-42c0-8bd1-6f37c785ae9f
>   state_topic: "/sensor/sensorid/counter"
>   device_class: energy
>   name: "Summe Stromverbrauch"
>   qos: 0
>   unit_of_measurement: "Wh"
>   value_template: "{{ value_json[1] }}"
> 
> - platform: mqtt
>   unique_id: xxxxxxx-53ac-4a4a-bc0c-7c9f8fee2144
>   state_topic: "/sensor/sensorid/counter"
>   device_class: gas
>   name: "Summe Gasverbrauch"
>   qos: 0
>   unit_of_measurement: "m3"
>   value_template: '{{ value_json[1] }}'
> 
> - platform: mqtt
>   unique_id: xxxxxxxxx-6e24-42bf-b49f-2168ea27cf6b
>   state_topic: "/sensor/sensorid/counter"
>   name: "Summe Wasserverbrauch"
>   qos: 0
>   unit_of_measurement: "m3"
>   value_template: '{{ value_json[1] }}'
> ```

This is basically what this integration does, but automatically.

**Comment by vk2him** [comment]
> @vk2him Which version of HA are you using?
> 
> Could you test with the newest version 1.0.1? Can you add the debug logs?

I'm running 2021.12.10 - I loaded the newest version, looks like it can see my 3 x Flukso sensors from the following error that is now displayed in logs:

This error originated from a custom integration.

Logger: custom_components.flukso.discovery
Source: custom_components/flukso/discovery.py:355
Integration: Flukso (documentation, issues)
First occurred: 8:43:56 AM (18 occurrences)
Last logged: 8:43:56 AM

Could not convert config to to MQTT sensor config for id xxxxx1fad2e6701e5aa87ab0208187a9
Could not convert config to to MQTT sensor config for id xxxxx9347c8f5e886af1d95df7228ac0
Could not convert config to to MQTT sensor config for id xxxxx298ca289494c7109b1ea53efa7e

**Comment by bertouttier** [comment]
@vk2him You should use the device hash, not the sensor hash, in the configuration. You can find this hash on MQTT when subscribing to `/device/#`. The sensors should then be discovered automatically.
Let me know if this works for you.

**Comment by vk2him** [comment]
@bertouttier  I am not using the sensor hash - I am using the hash from /device/#  - there are two hashes under /device/#  - here is a redacted view from MQTT Explorer:

device
fe779fd84ce66d210be26fc6xxxx
config
sensor = {"mqtt":{"bridge_restart_timeout":30,"bridge_address":"api.flukso.net","bridge_port":8883,"bridge_keepalive":60},"1":{"id":"bc6291fad2e6701e5aa87ab020xxxxx","class":"analog","enable":1,"type":"electricity","function":"HWS","port":[1],"current":50,"rid":0,"data_type":"counter","voltage":240},"10":{"id":"f1be5939cb19f6c29005df4cxxxxx"},"3":{"id":"a2e8c6893fe8e11e7c17c1d1e6efxxxxx","class":"pulse"…
f9608fd6fe41357fc51a0e5xxxxxxx
config
kube = {"main":{"encryption":0,"max_nodes":30,"pair_group":212,"null_key":"0123456789abcdef0123456789abcdef","cache":"/usr/share/kube","collect_group":40,"key":"497dbbc8634b15cb6a88e1066xxxxxx"}}
sensor = {"53":{"id":"755256a871b0dc37e36309fbxxxx"},"43":{"id":"43df77ea804ebf3bd296cfd0xxxxx"},"63":{"id":"839911a4e32a63062517386e8xxxxx"},"47":{"id":"9af5d61e4f7c0988eeff7bbd53xxxxxx"},"37":{"id":"8bfd36840bc4335d474a98d1xxxxx"},"57":{"id":"a1d80f443f2f806073277563cxxxxx"},"27":{"id":"6002ad8813d5da6f40120e1e0xxxxxx"},"17":{"id":"9a8ae37d4b7e88581ad100c1xxxxx"},"13":{"id":"2669a59xxxx


To be clear, I'm using the /device/fe779fd84ce66d210be26fc6xxxx  hash - is this the one correct?

Thanks

**Comment by vk2him** [comment]
@bertouttier 
Here's an easier to see screenshot of MQQT Explorer pointed to my Flukso. I'm using fe779fd84ce66d210be26fc6xxxx and not sensor hashes.

![Screen Shot 244](https://user-images.githubusercontent.com/22878629/151767139-92b40c6d-5b77-4548-84f0-3b58a0c7e8a4.jpg)

**Comment by bertouttier** [comment]
@vk2him Thank you, that is helpful. Can you set the log level of the flukso component to debug and provide me the logs?

```
logger:
  default: warning
  logs:
    custom_components.flukso: debug
```

**Comment by vk2him** [comment]
Here's the detailed logs - note the last 3 errors are repeated many times:

Could not convert config to to MQTT sensor config for id bc6291fad2e6701e5aa87abxxxx
9:07:22 PM – (ERROR) Flukso (custom integration) - message first occurred at 9:07:22 PM and shows up 18 times

2022-01-31 21:07:17 DEBUG (MainThread) [custom_components.flukso.discovery] storing config type sensor for device fe779fd84ce66d210be26fxxxx

2022-01-31 21:07:22 DEBUG (MainThread) [custom_components.flukso.discovery] test tap pending, FLM02?
2022-01-31 21:07:22 DEBUG (MainThread) [custom_components.flukso.discovery] all configs and tap received
2022-01-31 21:07:22 ERROR (MainThread) [custom_components.flukso.discovery] Could not convert config to to MQTT sensor config for id bc6291fad2e6701e5aa87ab0xxxx

2022-01-31 21:07:22 DEBUG (MainThread) [custom_components.flukso.discovery] {'name': 'unknown electricity', 'device': {'connections': [], 'identifiers': {('flukso', 'fe779fd84ce66d210be26fxxx')}, 'manufacturer': 'Flukso', 'name': 'fe779fd84ce66d210be26fc6exxx', 'sw_version': 'unknown'}, 'enabled_by_default': True, 'platform': 'mqtt', 'state_topic': '/sensor/bc6291fad2e6701e5aa87axxxx/q1', 'state_class': None, 'qos': 0, 'force_update': True, 'unique_id': 'fe779fd84ce66d210be26fc6efxxxxx_bc6291fad2e6701e5aa87ab020xxxxxx_q1', 'icon': 'mdi:lightning-bolt', 'value_template': '{{ value.split(",")[1] | float }}'}

2022-01-31 21:07:22 ERROR (MainThread) [custom_components.flukso.discovery] Could not convert config to to MQTT sensor config for id 6143e9347c8f5e886af1d95dxxxx
2022-01-31 21:07:22 DEBUG (MainThread) [custom_components.flukso.discovery] {'name': 'unknown electricity', 'device': {'connections': [], 'identifiers': {('flukso', 'fe779fd84ce66d210be26fcxxx')}, 'manufacturer': 'Flukso', 'name': 'fe779fd84ce66d210be26fc6exxxxx', 'sw_version': 'unknown'}, 'enabled_by_default': True, 'platform': 'mqtt', 'state_topic': '/sensor/6143e9347c8f5e886af1d95dxxxx/pminus', 'state_class': None, 'qos': 0, 'force_update': True, 'unique_id': 'fe779fd84ce66d210be26fc6efxxxxx_6143e9347c8f5e886af1d95xxxx_pminus', 'icon': 'mdi:lightning-bolt', 'value_template': '{{ value.split(",")[1] | float }}'}

2022-01-31 21:07:22 ERROR (MainThread) [custom_components.flukso.discovery] Could not convert config to to MQTT sensor config for id 48106298ca289494c7109b1eaxxxxxx
2022-01-31 21:07:22 DEBUG (MainThread) [custom_components.flukso.discovery] {'name': 'unknown electricity', 'device': {'connections': [], 'identifiers': {('flukso', 'fe779fd84ce66d210be26fc6xxxxx')}, 'manufacturer': 'Flukso', 'name': 'fe779fd84ce66d210be26xxxxx', 'sw_version': 'unknown'}, 'enabled_by_default': True, 'platform': 'mqtt', 'state_topic': '/sensor/48106298ca289494c7xxxx/q1', 'state_class': None, 'qos': 0, 'force_update': True, 'unique_id': 'fe779fd84ce66d210be26fc6exxxx_48106298ca289494c7109xxxx_q1', 'icon': 'mdi:lightning-bolt', 'value_template': '{{ value.split(",")[1] | float }}'}

**Comment by bertouttier** [comment]
Thans @vk2him , that is very helpful. I will have a look and post an update if I have a new version.

**Comment by bertouttier** [comment]
@vk2him can you test with version 1.0.2?

**Comment by vk2him** [comment]
@bertouttier - version 1.0.2 doesn't seem to be available so removed the integration, rebooted, then copied the modified version of discovery.py you just did to overwrite the old version, then rebooted and tried to add the integration again.

I can't load the integration now - after selection Flukso from the Integrations page it pops up a window with the following error:

Error
Config flow could not be loaded

The logfile shows this error:

Error handling request
8:45:13 AM – (ERROR) Flukso (custom integration)

Logger: aiohttp.server
Source: custom_components/flukso/__init__.py:9
Integration: Flukso (documentation, issues)
First occurred: 8:45:13 AM (1 occurrences)
Last logged: 8:45:13 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 130, in post
    return await super().post(request)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 203, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 221, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 718, in async_create_flow
    integration.get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 530, in get_platform
    cache[full_name] = self._import_platform(platform_name)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 535, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/config/custom_components/flukso/__init__.py", line 9, in <module>
    from .discovery import async_discover_device
  File "/config/custom_components/flukso/discovery.py", line 406
    dts = _get_sensor_detail(sensor, DATA_TYPE_MAP_FLM03):
                                                         ^
SyntaxError: invalid syntax

**Comment by bertouttier** [comment]
@vk2him sorry about that, version 1.0.3 pushed.

**Comment by vk2him** [comment]
@bertouttier - thank you - it's working perfectly now ... as a suggestion for your documentation, it would be nice if you documented how to obtain the /device hash as people may assume its the sensor hash? Thanks Again!

**Comment by bertouttier** [comment]
@vk2him thanks for your help and your suggestion. I will update the docs!
