### ISSUE TITLE
Integration fails in current homeassistant version

### ISSUE THREAD

**Issue by limpens** [bertouttier/flukso-hacs#15]
Using homeassistant core 2024.5.2, the integration crashes:

```
2024-05-09 17:58:26.995 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Flukso <ID> for flukso
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 575, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/flukso/__init__.py", line 32, in async_setup_entry
    await async_discover_device(hass, entry)
  File "/config/custom_components/flukso/discovery.py", line 541, in async_discover_device
    assert config_futures[CONFTYPE_SENSOR] in done
AssertionError

```

Has been working properly using the previous version(s) of homeassistant. Removing/re-installing did not resolve the issue.

**Comment by limpens** [comment]
Closing the issue, deleted the flukso-device from HA configuration, stopped the container and deleted the images, just to reinstall the container.

The flukso device was auto-discovered and all entities available again.
