### ISSUE TITLE
Latest version of Home Assistants breaks Flukso integration

### ISSUE THREAD

**Issue by freekbe** [bertouttier/flukso-hacs#16]
Flukso integration is working fine on HAOS 13.1 with Core version 2024.9.3
Upgrading to 13.2 and 2024.11.1 breaks the integration.

Error message: Error occurred loading flow for integration flukso: No module named 'homeassistant.components.mqtt.mixins'

I tried to install Flukso on a blank HAOS installation running the latest versions. After installing Flukso and restarting HA, there are error messages in the log files (even before adding a Flukso device):

```
2024-11-13 11:33:59.824 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-11-13 11:33:59.826 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration flukso which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-11-13 11:34:10.256 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration flukso: No module named 'homeassistant.components.mqtt.mixins'
2024-11-13 11:34:10.256 ERROR (MainThread) [homeassistant.config_entries] Error occurred loading flow for integration flukso: No module named 'homeassistant.components.mqtt.mixins'
2024-11-13 11:34:10.257 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3247, in _load_integration
    await integration.async_get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1104, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1199, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'homeassistant.components.mqtt.mixins'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1301, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1326, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1518, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3268, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3254, in _load_integration
    raise data_entry_flow.UnknownHandler from err
homeassistant.data_entry_flow.UnknownHandler
2024-11-13 11:34:10.268 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3247, in _load_integration
    await integration.async_get_platform("config_flow")
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1104, in async_get_platform
    platforms = await self.async_get_platforms((platform_name,))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1199, in async_get_platforms
    platforms[platform_name] = await future
                               ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'homeassistant.components.mqtt.mixins'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1301, in async_init
    flow, result = await self._async_init(flow_id, handler, context, data)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1326, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1518, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3268, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 3254, in _load_integration
    raise data_entry_flow.UnknownHandler from err
homeassistant.data_entry_flow.UnknownHandler
```

**Comment by fabricecatherine03** [comment]
Dear. Thanks for your HACS development.
I encounter exactly the same issue as above with the same HAS OS

**Comment by bertouttier** [comment]
Hi all,
It should be fixed in the new release 1.0.13. Let me know if that helps for you.
Kind regards

**Comment by freekbe** [comment]
@bertouttier I can confirm that the issue is fixed in 1.0.13
Thank you very much!

**Comment by fabricecatherine03** [comment]
@bertouttier : Many thanks Bert : it is working nicely. Good job here !

**Comment by fabricecatherine03** [comment]
Hi Bert. I am trying to delete the configured device in order to reinstall it again (just for testing). When I try to delete it, I see this error message (and the deletion does not finalized : all the devices remains visible)
```
Enregistreur: homeassistant.components.sensor
Source: components/sensor/__init__.py:571
intégration: Capteur ([documentation](https://www.home-assistant.io/integrations/sensor), [problèmes](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
S'est produit pour la première fois: 09:03:44 (2 occurrences)
Dernier enregistrement: 09:03:54

Entity sensor.smart_main_gas_gauge (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using state class 'measurement' which is impossible considering device class ('gas') it is using; expected None or one of 'total', 'total_increasing'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/bertouttier/flukso-hacs/issues
```

I have also noticed this warning:

```
Enregistreur: homeassistant.const
Source: helpers/deprecation.py:222
S'est produit pour la première fois: 09:37:44 (1 occurrences)
Dernier enregistrement: 09:37:44

POWER_VOLT_AMPERE_REACTIVE was used from flukso, this is a deprecated constant which will be removed in HA Core 2025.9. Use UnitOfReactivePower.VOLT_AMPERE_REACTIVE instead, please report it to the author of the 'flukso' custom integration
```
Thanks for your help.
