### ISSUE TITLE
binary_sensor and sensor error when configuring (FLM02A) 

### ISSUE THREAD

**Issue by bollewolle** [bertouttier/flukso-hacs#2]
Hi,

Somehow this integration is returning errors for me. I have a Flukso FLM02A. Below the details and at the end the error messages I'm getting.

I've implemented the integration via HACS, it's version 1.0.4:
<img width="204" alt="image" src="https://user-images.githubusercontent.com/368306/153703720-ae1065f0-af90-4db8-aa44-bedfda5957f0.png">

I also posted a conversation on the Flukso forum [here](https://www.flukso.net/content/flukso-home-assistant#comment-7124) about this issue, you can see my post of "10/02/2022 - 18:53" and later.

My Mosquitto broker Add-On is also the latest version 6.0.1 and has the following config:
```
logins: []
customize:
  active: true
  folder: mosquitto
certfile: fullchain.pem
keyfile: privkey.pem
require_certificate: false
```

Checking the broker with MQTT Explorer shows the data from Flukso coming in:
<img width="565" alt="image" src="https://user-images.githubusercontent.com/368306/153703546-84694488-ef0d-46d2-9f63-92a2ed8653b1.png">

I've then used the device hash, see green arrow in screenshot, to add the Flukso integration. It says that it's created but the logs return error messages. I've activated the Debug logger for the Flukso integration and this is the output (note that the device has has been anonymized with the x's at the end):

```
2022-02-12 09:21:09 INFO (MainThread) [custom_components.flukso.config_flow] Creating new entry for Flukso d4599ea546cb8aacff3bb18bxxxxxxxx
2022-02-12 09:21:13 DEBUG (MainThread) [custom_components.flukso.discovery] test tap pending, FLM02?
2022-02-12 09:21:13 DEBUG (MainThread) [custom_components.flukso.discovery] all configs and tap received
2022-02-12 09:21:13 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up flukso platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/flukso/binary_sensor.py", line 10, in async_setup_entry
    configs = get_entities_for_platform(
  File "/config/custom_components/flukso/discovery.py", line 443, in get_entities_for_platform
    entities.extend(_get_binary_sensor_entities(entry_data, device_info))
  File "/config/custom_components/flukso/discovery.py", line 287, in _get_binary_sensor_entities
    for sensor in entry_data["sensor"].values():
KeyError: 'sensor'
2022-02-12 09:21:13 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up flukso platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/flukso/sensor.py", line 10, in async_setup_entry
    configs = get_entities_for_platform("sensor", hass.data[DOMAIN][entry.entry_id])
  File "/config/custom_components/flukso/discovery.py", line 445, in get_entities_for_platform
    entities.extend(_get_sensor_entities(entry_data, device_info))
  File "/config/custom_components/flukso/discovery.py", line 401, in _get_sensor_entities
    for sensor in entry_data["sensor"].values():
KeyError: 'sensor'
```

Anything I'm doing wrong? Any additional information you might need for this issue to find the source of the error? Just let me know and I'll provide it or test it.

Many thanks in advance.

**Comment by bollewolle** [comment]
This can be closed, I found the issue, I'll provide feedback for future reference.

I had set the Mosquitto Add-On to no longer be password protected but it turned out the the Mosquitto integration itself still was trying to signin with a password. Since that of course no longer was necessary, no data was being received in Home Assistant as a whole, with as a result the above issues with the Flukso integration as well. So in the end it was, as per usual, my mistake due to an oversight. But the integration is now working correctly, awesome! Thanks.
